"""Unit tests for the pedidos Lambda handler."""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest


@pytest.fixture(autouse=True)
def mock_env(monkeypatch):
    monkeypatch.setenv("SQLSERVER_CONNECTION_STRING", "mssql+pymssql://u:p@host:1433/db")


@pytest.fixture
def mock_db():
    with patch("src.service.get_cursor") as m:
        cursor = MagicMock()
        conn = MagicMock()
        m.return_value.__enter__ = MagicMock(return_value=(cursor, conn))
        m.return_value.__exit__ = MagicMock(return_value=False)
        yield cursor, conn


def test_empty_lineas():
    from src.handler import lambda_handler

    result = lambda_handler({"encabezado": {}, "lineas": []}, None)
    assert result["ok"] is False
    assert "al menos una línea" in result["errores"][0]


def test_missing_cod_cte():
    from src.handler import lambda_handler

    with patch("src.handler.crear_pedido") as mock_crear:
        from src.service import ErrorValidacion
        mock_crear.side_effect = ErrorValidacion(["cod_cte es requerido"])

        result = lambda_handler(
            {"encabezado": {"cod_ven": "V01"}, "lineas": [{"cod_pro": "X"}]},
            None,
        )
        assert result["ok"] is False
        assert "cod_cte" in result["errores"][0]


def test_success():
    from src.handler import lambda_handler

    # NUMTRA now comes from crear_pedido's result (generated by the sequence).
    with patch("src.handler.crear_pedido") as mock_crear:
        mock_crear.return_value = {"numtra": "PIA-0000000102", "num_lineas": 1}

        result = lambda_handler(
            {
                "encabezado": {"cod_cte": "100", "cod_ven": "V01"},
                "lineas": [{"cod_pro": "P1", "ped_caj": 1, "fac_emp": 12, "val_cto": 5.0}],
            },
            None,
        )
        assert result["ok"] is True
        assert result["numtra"] == "PIA-0000000102"


def test_lista_precio_requires_cod_cte():
    from src.handler import lambda_handler

    result = lambda_handler({"action": "lista_precio"}, None)
    assert result["ok"] is False
    assert "cod_cte" in result["errores"][0]


def test_lista_precio_success():
    from src.handler import lambda_handler

    cursor = MagicMock()
    cursor.fetchone.return_value = {"ListaPrecio": "LP_AUTOMA"}
    cm = MagicMock()
    cm.__enter__ = MagicMock(return_value=(cursor, MagicMock()))
    cm.__exit__ = MagicMock(return_value=False)

    with patch("db.get_cursor", return_value=cm):
        result = lambda_handler({"action": "lista_precio", "cod_cte": "1044086"}, None)

    assert result["ok"] is True
    assert result["cod_cte"] == "1044086"
    assert result["lista_precio"] == "LP_AUTOMA"


def test_lista_precio_client_not_found():
    from src.handler import lambda_handler

    cursor = MagicMock()
    cursor.fetchone.return_value = None
    cm = MagicMock()
    cm.__enter__ = MagicMock(return_value=(cursor, MagicMock()))
    cm.__exit__ = MagicMock(return_value=False)

    with patch("db.get_cursor", return_value=cm):
        result = lambda_handler({"action": "lista_precio", "cod_cte": "9999999"}, None)

    assert result["ok"] is False
    assert "no encontrado" in result["errores"][0]


def test_lista_precio_empty_returns_error():
    from src.handler import lambda_handler

    cursor = MagicMock()
    cursor.fetchone.return_value = {"ListaPrecio": ""}
    cm = MagicMock()
    cm.__enter__ = MagicMock(return_value=(cursor, MagicMock()))
    cm.__exit__ = MagicMock(return_value=False)

    with patch("db.get_cursor", return_value=cm):
        result = lambda_handler({"action": "lista_precio", "cod_cte": "1044086"}, None)

    assert result["ok"] is False
    assert "ListaPrecio" in result["errores"][0]


def test_insert_timeout_rolls_back_and_returns_504():
    """A hung INSERT (interrupted by the query timeout) → rollback + 504 error."""
    import pymssql
    from src.handler import lambda_handler

    cursor = MagicMock()
    conn = MagicMock()

    # Validation queries succeed: client exists + product exists.
    cursor.fetchone.side_effect = [
        {"CodCte": "100"},              # client-exists check
        {"CodPro": "P1", "FacEmpaque": 12},  # product lookup
        {"next_val": 102},             # NEXT VALUE FOR (sequence)
    ]

    # In _insertar_pedido the statement order is: SET LOCK_TIMEOUT, NEXT VALUE
    # FOR, header INSERT, then the detail-line INSERT. The line INSERT hangs and
    # SQL Server / pymssql interrupts it (OperationalError).
    cursor.execute.side_effect = [
        None,  # _validar_pedido: client-exists SELECT
        None,  # _validar_pedido: product SELECT
        None,  # _insertar_pedido: SET LOCK_TIMEOUT + XACT_ABORT
        None,  # _insertar_pedido: NEXT VALUE FOR
        None,  # _insertar_pedido: header INSERT
        pymssql.OperationalError("DB-Lib error: timeout"),  # line INSERT → interrupted
    ]

    cm = MagicMock()
    cm.__enter__ = MagicMock(return_value=(cursor, conn))
    cm.__exit__ = MagicMock(return_value=False)

    with patch("service.get_cursor", return_value=cm):
        result = lambda_handler(
            {
                "encabezado": {"cod_cte": "100", "cod_ven": "V01", "val_tot": 5.0},
                "lineas": [
                    {"cod_pro": "P1", "ped_caj": 1, "fac_emp": 12, "val_cto": 5.0, "val_vtc": 5.0}
                ],
            },
            None,
        )

    assert result["ok"] is False
    assert result["status"] == 504
    conn.rollback.assert_called_once()
    conn.commit.assert_not_called()
